### ISSUE TITLE
Story: Product Overview 

### ISSUE THREAD

**Issue by amsiotdeveloper** [OnionIoT/documentation#113]
# **The Story for a New Chapter:**
### **Task Owner:**
Who owns this task and will approve the final deliverables? 
Lazar

###  1. How does this task relate to the value track(s)?
- All of the effort we put into improving our product lines should provide value to our customers.
- We need to be able to clearly articulate the value each improvement will provide in the following three value tracks:
1. Development
2. Deployment
3. Production
This chapter provides an overview of the modules which helps users decide which one is best suited for the development needs.   These are articles are targeting users early in the decision process when they are trying to figure out what module to develop with. 
        
###  2. Create a short statement explaining the objectives and goals for this Chapter.

The objectives of this chapter is to provide provide a comprehensive overview of the options available to a new user  and provide the with high level information they would use in their decision process.

- The goal is to utilize as much existing content as possible so we can progress quickly through these articles. 
- Articles should be succinct, and minimalist.  

### 3. **Reference Material:**
- Provide hyperlinks for helpful and related information. 
https://docs.google.com/document/d/1N0GZG83dOvpB2MxFTK3Ez3AGx8D9avBp6x9aHxjGCRg/edit

# **The Workflow:**
- [ ] Subtask 1: Omega2: Documentation Roadmap reference 2.1 Ticket #114
- [x] Subtask 2: Omega2 Mechanical: Documentation Roadmap reference 2.1.1 Ticket #115 
- [x] Subtask 3: Omega2: Electrical Specifications: Documentation Roadmap reference 2.1.2 Ticket #116 
- [x] Subtask 4: Omega2S: Documentation Roadmap reference 2.2 Ticket #117 
- [x] Subtask 5: Omega2S: Mechanical: Documentation Roadmap reference 2.2.1 Ticket #118 
- [x] Subtask 6: Omega2S: Electrical Specifications: Documentation Roadmap reference 2.2.2 Ticket #119
