### ISSUE TITLE
Story: Quickstart Chapter

### ISSUE THREAD

**Issue by amsiotdeveloper** [OnionIoT/documentation#120]
# **The Story for a New Chapter:**
### **Task Owner:**
Who owns this task and will approve the final deliverables? 
Lazar

###  1. How does this task relate to the value track(s)?
- All of the effort we put into improving our product lines should provide value to our customers.
- We need to be able to clearly articulate the value each improvement will provide in the following three value tracks:
1. Development
2. Deployment
3. Production
This chapter provides a Quickstart guide for new users starting to develop with the Omega platform. 
        
###  2. Create a short statement explaining the objectives and goals for this Chapter.

The objectives of this chapter is to provide an easy to follow step by step process to help new users get started.
The goal is to provide new users with a good experience unboxing their new Omega products.

- The goal is to utilize as much existing content as possible.
- Articles should be succinct, and minimalist.  

### 3. **Reference Material:**
- Provide hyperlinks for helpful and related information. 
https://docs.google.com/document/d/1h7JF9ceYgBxK7cVass_cCJOiFn6moJTYrZp7dWuJpKI/edit

https://docs.onion.io/omega2-docs/first-time-setup-command-line.html

# **The Workflow:**
- [x] Subtask 1: Intro - Power Up: Documentation Roadmap reference 3.1 Ticket #125 
- [x] Subtask 2: Serial Command Line: Documentation Roadmap reference 3.2 Ticket #126 
- [x] Subtask 3: Setup WiFi: Documentation Roadmap reference 3.3 Ticket #x 
- [x] Subtask 4: Hello World Example: Documentation Roadmap reference 3.4 Ticket #x 
- [x] Subtask 5: Suggested Reading: Documentation Roadmap reference 3.5 Ticket #x
