### ISSUE TITLE
Task: Compile a package

### ISSUE THREAD

**Issue by amsiotdeveloper** [OnionIoT/documentation#22]
---
name: Documentation Article Tasklist
about: The purpose of this template is to manage the workflow process for creating articles.
title: ''
labels: ''
assignees: ''

---
# **The Task**
### **Task Owner:**
Who owns this task and will approve the final deliverables? 

Lazar

###  1. How does this task relate to the value track(s)?
- All of the effort we put into improving our product lines should provide value to our customers.
- We need to be able to clearly articulate the value each improvement will provide in the following three value tracks:
  1. Development – the goal is to help developers learn the process for creating packages.
  2. Deployment – packages are an important part of preparing code for deployment and production 
  3. Production
                    
###  2. Create a short statement explaining the objectives and goals for this ticket.
   - This chapter will focus on the process for compiling a package 
   
### 3. **Reference Material:**
- Provide hyperlinks and description for helpful and related information.
   https://docs.google.com/document/d/1I4uVpQeeZqDSkYZ6AsAw5vFScbymLYmL8slFtXikJ7E/edit?pli=1#heading=h.wo64beb0b8k8

###  1. What are the task owners expectations? 

- Focus this article on the process to compile a package. 

###  2. What does the task owner require for a successful completion of the ticket?
    i.e. sample code, drawings, documents etc.
- provide a clear process and outline how to create a package.
- ~500 words 

# **Date Required By:**
###  1. When is the scope required to be completed?
no specified date
###  2. Is this a hard date?  Specify if the task is a dependency of another task or if it will impact a customer requirement.
no dependencies 

# **The Workflow**
     
## **Backlog Column: List of Subtasks**
- [x] Subtask 1 (Workflow Reference 1): Idea dump from subject matter expert is completed.
- Create document of ideas for an outline of the new article. 
- Deliverable: google doc 
- [x] Subtask 2 (Workflow Reference 2): Technical Writer has created the outline of article and high level ideas for review.
- Revise and expand on the provided google doc
- Deliverable: google doc outline  
- [x] Subtask 3 (Workflow Reference 3): SME has reviewed and approved the ticket "Ready for Development" 

## **Ready for Development Column: List of Subtasks**
- [x] Subtask 1(Workflow Reference 4): PM has assigned the task to a technical writer.
- [x] Subtask 2(Workflow Reference 5): Technical writer has moved ticket to "In Progress" when work begins. 

## **In Progress Column: List of Subtasks**
- Technical writer is creating content.
- Technical writer will push the ticket to "In Review" when the articles is ready for review.
- An iterative review process is expected.

## **In Review Column: List of Subtasks**
- [x] Subtask 1(Workflow Reference 6): Initial Review has been **Approved** by PM.
- [x] Subtask 2(Workflow Reference 7): Review has been **Approved** by SME.
- SME moves ticket to "Approved for Production"

## **Approved for Production Column: List of Subtasks**
- [x] Subtask 1(Workflow Reference 8): Technical writer has sent Pull Request.
- [x] Subtask 2(Workflow Reference 9): SME has committed the document to the repo.
- SME moves the ticket to "Completed" column.

**Comment by amsiotdeveloper** [comment]
this ticket got pushed into development before it was approved/assigned.  please follow the process - tickets should not be moved out of the "No Status" and "Backlog" columns.  The PM is the only one who will move tickets out of those 2 columns. 

- I have updated the ticket and assigned it to @iammuze

**Comment by iammuze** [comment]
Hi, @greenbreakfast modified the outlines, please review.

**Comment by greenbreakfast** [comment]
I've added another round of comments to the outline cc @iammuze

**Comment by iammuze** [comment]
Hi, @greenbreakfast I have attended the latest comments.

**Comment by greenbreakfast** [comment]
outline approved!

**Comment by iammuze** [comment]
Hi @amsiotdeveloper  this document is ready for the initial review.

**Comment by amsiotdeveloper** [comment]
Good work @iammuze 
I have finished my review of this article. 
Comments included in the doc.  Let me know if you have questions.

**Comment by iammuze** [comment]
Hi @amsiotdeveloper all clear on my end, no questions for now. thanks

**Comment by amsiotdeveloper** [comment]
@iammuze additional comments have been added by both @greenbreakfast and I.

@greenbreakfast I think we could use a little more direction from you with regards to the comments about the docker example then @iammuze should be able to finalize this article.

**Comment by greenbreakfast** [comment]
@amsiotdeveloper added my preferred approach for docker to the article

**Comment by iammuze** [comment]
Hi @greenbreakfast, the comments have been resolved. I have a query within the docs.

**Comment by greenbreakfast** [comment]
@iammuze responded in the document

**Comment by iammuze** [comment]
@greenbreakfast  suggestions accepted. Do you think it is good to go now? Will it also be pushed under `docs/packages/`?

**Comment by greenbreakfast** [comment]
@iammuze i've made a few more edits in the first 2 sections. After that, this article is good go. Please put it at `docs/packages/compile-package.md`

**Comment by iammuze** [comment]
Hi @greenbreakfast created a PR please check
