### ISSUE TITLE
Task: Create a Custom Package

### ISSUE THREAD

**Issue by amsiotdeveloper** [OnionIoT/documentation#31]
---
name: Documentation Article Tasklist
about: The purpose of this template is to manage the workflow process for creating articles.
title: ''
labels: ''
assignees: ''

---
# **The Task**
### **Task Owner:**
Who owns this task and will approve the final deliverables? 

Lazar

###  1. How does this task relate to the value track(s)?
- All of the effort we put into improving our product lines should provide value to our customers.
- We need to be able to clearly articulate the value each improvement will provide in the following three value tracks:
1. Development - having a clear understanding of Opkg is very important for new developers
2. Deployment - Opkg are instrumental in the management and deployment of firmware
3. Production
                    
###  2. Create a short statement explaining the objectives and goals for this ticket.
- The goal is to make it easy for users to create custom packages.
- 
### 3. **Reference Material:**
- Provide hyperlinks and description for helpful and related information.
https://docs.google.com/document/d/1WgRpjrpaq_3ylE1A-xweDexls2jhbJabQNkmCvFiM34/edit?pli=1

###  1. What are the task owners expectations? 
- Provide an article that makes it easy for users to understand how to create a custom package.
- provide a clear succinct process 

###  2. What does the task owner require for a successful completion of the ticket?
    i.e. sample code, drawings, documents etc.
- approximately 500 word article 

# **Date Required By:**
###  1. When is the scope required to be completed?
no specified date
###  2. Is this a hard date?  Specify if the task is a dependency of another task or if it will impact a customer requirement.
no dependencies 

# **The Workflow**
     
## **Backlog Column: List of Subtasks**
- [x] Subtask 1 (Workflow Reference 1): Idea dump from subject matter expert is completed.
- Create document of ideas for an outline of the new article. 
- Deliverable: google doc 
- [x] Subtask 2 (Workflow Reference 2): Technical Writer has created the outline of article and high level ideas for review.
- Revise and expand on the provided google doc
- Deliverable: google doc outline  
- [x] Subtask 3 (Workflow Reference 3): SME has reviewed and approved the ticket "Ready for Development" 

## **Ready for Development Column: List of Subtasks**
- [x] Subtask 1(Workflow Reference 4): PM has assigned the task to a technical writer.
- [x] Subtask 2(Workflow Reference 5): Technical writer has moved ticket to "In Progress" when work begins. 

## **In Progress Column: List of Subtasks**
- Technical writer is creating content.
- Technical writer will push the ticket to "In Review" when the articles is ready for review.
- An iterative review process is expected.

## **In Review Column: List of Subtasks**
- [x] Subtask 1(Workflow Reference 6): Initial Review has been **Approved** by PM.
- [x] Subtask 2(Workflow Reference 7): Review has been **Approved** by SME.
- SME moves ticket to "Approved for Production"

## **Approved for Production Column: List of Subtasks**
- [x] Subtask 1(Workflow Reference 8): Technical writer has sent Pull Request.
- [x] Subtask 2(Workflow Reference 9): SME has committed the document to the repo.
- SME moves the ticket to "Completed" column.

**Comment by amsiotdeveloper** [comment]
@iammuze and @greenbreakfast will review/revise the outline.
After the outline has been agreed, then @iammuze will continue with the content.

**Comment by greenbreakfast** [comment]
@iammuze added comments to outline. please review

**Comment by iammuze** [comment]
@greenbreakfast modified the outlines, please review.

**Comment by greenbreakfast** [comment]
I've added another round of comments to the outline cc @iammuze

**Comment by iammuze** [comment]
Hi, @greenbreakfast I have attended the latest comments.

**Comment by greenbreakfast** [comment]
@iammuze I've added a few more comments. Once you address them, feel free to proceed with the article

**Comment by iammuze** [comment]
Hi @amsiotdeveloper , this doc is ready for initial review.

**Comment by amsiotdeveloper** [comment]
@iammuze I have reviewed the article.  Suggestions and comments have been added to the doc for your revision.

**Comment by iammuze** [comment]
@amsiotdeveloper comments and suggestions have been addressed. 

Hi @greenbreakfast now, you can review it.

**Comment by greenbreakfast** [comment]
@iammuze i've reviewed the draft and added comments

@amsiotdeveloper I agree that we should be clear on the method we recommend to build packages. This article is meant to introduce the concept and structure of a custom package. I think a separate article - on compiling packages perhaps - should introduce the sdk/build system etc. 
I've added this in comments in the draft.

**Comment by iammuze** [comment]
Hi, @greenbreakfast comments have been addressed.

**Comment by amsiotdeveloper** [comment]
@greenbreakfast are you suggesting we add the build system introduction to the compiling packages article here in ticket 22? 

https://docs.google.com/document/d/1Wg-UE7-tAQxdZwGA5cr8Ars8Qkv3IbFtr99wRwGap9g/edit

My suggestion is to introduced the recommended solution for the build system, then introduce a new chapter later(if needed) to address other build system options/configurations. But let's stay focused on the recommended solution.

**Comment by iammuze** [comment]
Hi @greenbreakfast I have updated the `create a custom package` section with the given pointers.

**Comment by iammuze** [comment]
Hi @amsiotdeveloper, please use the updated link for the `Compile A Package` chapter: https://docs.google.com/document/d/1C_scQXgbSaBRwDzTBTTTT9AG9SyoByXNtkvnIhw1O-U/edit?usp=sharing.

**Comment by greenbreakfast** [comment]
Hi @iammuze, see updates in the doc

@amsiotdeveloper re: 
> are you suggesting we add the build system introduction to the compiling packages article here in ticket 22?

Yes, we've reworked the article outline and it includes a brief introduction about the SDK.
See this section in the outline https://docs.google.com/document/d/1I4uVpQeeZqDSkYZ6AsAw5vFScbymLYmL8slFtXikJ7E/edit#heading=h.7w06154mv3nf

**Comment by iammuze** [comment]
Hi, @greenbreakfast the comments have been addressed.

**Comment by greenbreakfast** [comment]
@iammuze I've responded to the open comments and asked @amsiotdeveloper to weigh in as well.
Once that last item is settled, we'll be ready for a PR

**Comment by amsiotdeveloper** [comment]
@iammuze I agree with @greenbreakfast comments.  Please clean up the bottom of the article as per the comments in the article.

**Comment by iammuze** [comment]
@greenbreakfast @amsiotdeveloper, I've addressed the latest comment in the article section and converted it into Markdown format. Is it ready to be pushed? Please let me know the exact location within the packages directory where it should be pushed.

**Comment by greenbreakfast** [comment]
@iammuze please put it at `docs/packages/custom-package.md`
