### ISSUE TITLE
Task: Deploy a Package

### ISSUE THREAD

**Issue by amsiotdeveloper** [OnionIoT/documentation#32]
---
name: Documentation Article Tasklist
about: The purpose of this template is to manage the workflow process for creating articles.
title: ''
labels: ''
assignees: ''

---
# **The Task**
### **Task Owner:**
Who owns this task and will approve the final deliverables? 

Lazar

###  1. How does this task relate to the value track(s)?
- All of the effort we put into improving our product lines should provide value to our customers.
- We need to be able to clearly articulate the value each improvement will provide in the following three value tracks:
        1. Development -
        2. Deployment -  understanding how to deploy a package is important for users in the development stage so they can learn how to deploy a package.
        3. Production
                    
###  2. Create a short statement explaining the objectives and goals for this ticket.
- The goal is to provide an outline explaining how to deploy a package for production
- 
### 3. **Reference Material:**
- Provide hyperlinks and description for helpful and related information.
https://docs.google.com/document/d/10iAxTZkmJFSO1HmSFezPJ_LCELzYLn0lFHGfC0ODkTg/edit

###  1. What are the task owners expectations? 
- Create a process for users to learn how to deploy a package.

###  2. What does the task owner require for a successful completion of the ticket?
    i.e. sample code, drawings, documents etc.
- The user should be able to read the article and acquire the knowledge necessary to deploy a package.
- The user should be able to follow the process to deploy a package.
- approximately 500 word article 

# **Date Required By:**
###  1. When is the scope required to be completed?
no specified date
###  2. Is this a hard date?  Specify if the task is a dependency of another task or if it will impact a customer requirement.
no dependencies 

# **The Workflow**
     
## **Backlog Column: List of Subtasks**
- [x] Subtask 1 (Workflow Reference 1): Idea dump from subject matter expert is completed.
- Create document of ideas for an outline of the new article. 
- Deliverable: google doc 
- [x] Subtask 2 (Workflow Reference 2): Technical Writer has created the outline of article and high level ideas for review.
- Revise and expand on the provided google doc
- Deliverable: google doc outline  
- [x] Subtask 3 (Workflow Reference 3): SME has reviewed and approved the ticket "Ready for Development" 

## **Ready for Development Column: List of Subtasks**
- [x] Subtask 1(Workflow Reference 4): PM has assigned the task to a technical writer.
- [x] Subtask 2(Workflow Reference 5): Technical writer has moved ticket to "In Progress" when work begins. 

## **In Progress Column: List of Subtasks**
- Technical writer is creating content.
- Technical writer will push the ticket to "In Review" when the articles is ready for review.
- An iterative review process is expected.

## **In Review Column: List of Subtasks**
- [x] Subtask 1(Workflow Reference 6): Initial Review has been **Approved** by PM.
- [ ] Subtask 2(Workflow Reference 7): Review has been **Approved** by SME.
- SME moves ticket to "Approved for Production"

## **Approved for Production Column: List of Subtasks**
- [ ] Subtask 1(Workflow Reference 8): Technical writer has sent Pull Request.
- [ ] Subtask 2(Workflow Reference 9): SME has committed the document to the repo.
- SME moves the ticket to "Completed" column.

**Comment by greenbreakfast** [comment]
outline approved ✅

**Comment by iammuze** [comment]
Hi, @amsiotdeveloper  this document is ready for your initial review

**Comment by iammuze** [comment]
Hi @amsiotdeveloper, in this document, the content was created based on the approved outline. The introduction section clearly explains what this document covers. Please feel free to re-check the outline document as I have finalized this content based on @greenbreakfast inputs. Whatever I have covered in this document has been discussed briefly in the outline with Lazar. 

What I see here is that your ideas are conflicting with @greenbreakfast 's ideas at the moment. You can compare the **outline** and **document**. I am confident that the content is fine and does the justice. Rest, I am open to feedback. Please let me know.

**Comment by iammuze** [comment]
Hi @greenbreakfast  and @amsiotdeveloper the comments have been addressed, and the recently suggested changes have been added.

**Comment by amsiotdeveloper** [comment]
@iammuze that is a huge improvement - thank you.
@greenbreakfast  please review ticket 32 for your approval. 

This is our last article for this chapter so I think we can close out the story ticket after this article is approved.

**Comment by greenbreakfast** [comment]
@amsiotdeveloper @iammuze comments and suggestions have been added to the draft

**Comment by iammuze** [comment]
@greenbreakfast comments have been addressed

**Comment by greenbreakfast** [comment]
hi @iammuze , added another round of suggestions. Will be ready for a PR after those are handled

**Comment by greenbreakfast** [comment]
merged pr, thanks
