### ISSUE TITLE
Story: OpenWRT Packages

### ISSUE THREAD

**Issue by amsiotdeveloper** [OnionIoT/documentation#35]
# **The Story for a New Chapter:**
### **Task Owner:**
Who owns this task and will approve the final deliverables? 
Lazar

###  1. How does this task relate to the value track(s)?
- All of the effort we put into improving our product lines should provide value to our customers.
- We need to be able to clearly articulate the value each improvement will provide in the following three value tracks:
1. Development
2. Deployment
3. Production
            
### 3. **Reference Material:**
- Provide hyperlinks for helpful and related information. 

###  1. What are the task owners expectations? 
We have refined the process, but for the purpose of this ticket, please refer to ticket 17 for the scope.
We will use this ticket to exercise the new workflow and checkboxes below.

###  2. What does the task owner require for a successful completion of the ticket?
    i.e. sample code, drawings, documents etc.

# **Date Required By:**
###  1. When is the scope required to be completed?
No specified deadline
###  2. Is this a hard date?  Specify if the task is a dependency of another task or if it will impact a customer requirement.
No dependencies. 

# **The Workflow:**
- [x] Subtask 1 (Workflow reference 10): Subject expert created a document of ideas for the new chapter.
- [x] Subtask 2(Workflow reference 11): Technical Writer has created a list of articles that will go into the new chapter.
- [x] SME approved the chapter outline.

Subtask 3: PM will create List of tickets for the articles to be created in this chapter:
(Workflow reference 12)
- [x] Task 1 for Article 1: Getting Started Guide  - Ticket 28
- [x] Task 2 for Article 2: OPKG Package Manager - Ticket 29
- [x] Task 3 for Article 3: OPKG Package Manager - Ticket 31
- [x] Task 4 for Article 4: OPKG Package Manager - Ticket 22
- [ ] Task 5 for Article 5: OPKG Package Manager - Ticket 32

_(add more +/- tasks as needed.  One for each article.)_

**Comment by greenbreakfast** [comment]
Happy to mark this v1 of the packages chapter as complete!
