### ISSUE TITLE
Epic List: Hire Technical Writer

### ISSUE THREAD

**Issue by amsiotdeveloper** [OnionIoT/documentation#4]
- [x] Step 1: Create new Kanban project in github for documentation as per my example
- [ ] Step 2: do a test run on the documentation process and kanban flow
- [ ] Step 3: start to create backlog tickets 
- [ ] Step 4: onboard new technical writer
- [ ] Step 5: implement new process

**Comment by greenbreakfast** [comment]
@amsiotdeveloper next step: we'll work together to create a backlog

**Comment by amsiotdeveloper** [comment]
@greenbreakfast I think using your tag might be the only way that you will know when I respond?
