### ISSUE TITLE
How to Install and Use Packages

### ISSUE THREAD

**Issue by amsiotdeveloper** [OnionIoT/documentation#42]
# **The Task**
### **Task Owner:**
Who owns this task and will approve the final deliverables? 

Lazar

###  1. How does this task relate to the value track(s)?
- All of the effort we put into improving our product lines should provide value to our customers.
- We need to be able to clearly articulate the value each improvement will provide in the following three value tracks:
1. Development - the goal of this article is to help developers understand the process to install a package
2. Deployment
3. Production
           
###  2. Create a short statement explaining the objectives and goals for this ticket.
- The objective is to provide a process demonstrating how to install packages

### 3. **Reference Material:**
- Provide hyperlinks and description for helpful and related information.
- This is in the Software chapter 6 article 6.1 

Draft outline: 
https://docs.google.com/document/d/12uQheWQyFeYrzLzrT4BABxZaf6rIEp3l6nI8YqJb73c/edit?usp=sharing

###  1. What are the task owners expectations? 

- an article that is approximately 500 words or less as per the Omega Documentation Map for packages

###  2. What does the task owner require for a successful completion of the ticket?
    i.e. sample code, drawings, documents etc.
- after reading this article a user should have a clear understanding with a well defined process for installing packages

# **Date Required By:**
###  1. When is the scope required to be completed?
- no date has been specified 

###  2. Is this a hard date?  Specify if the task is a dependency of another task or if it will impact a customer requirement.
- there are no dependencies 

# **The Workflow**
     
## **Backlog Column: List of Subtasks**
- [ ] Subtask 1 (Workflow Reference 1): Idea dump from subject matter expert is completed.
- Create document of ideas for an outline of the new article. 
- Deliverable: google doc 
- [ ] Subtask 2 (Workflow Reference 2): Technical Writer has created the outline of article and high level ideas for review.
- Revise and expand on the provided google doc
- Deliverable: google doc outline  
- [ ] Subtask 3 (Workflow Reference 3): SME has reviewed and approved the ticket "Ready for Development" 

## **Ready for Development Column: List of Subtasks**
- [ ] Subtask 1(Workflow Reference 4): PM has assigned the task to a technical writer.
- [ ] Subtask 2(Workflow Reference 5): Technical writer has moved ticket to "In Progress" when work begins. 

## **In Progress Column: List of Subtasks**
- Technical writer is creating content.
- Technical writer will push the ticket to "In Review" when the articles is ready for review.
- An iterative review process is expected.

## **In Review Column: List of Subtasks**
- [ ] Subtask 1(Workflow Reference 6): Initial Review has been **Approved** by PM.
- [ ] Subtask 2(Workflow Reference 7): Review has been **Approved** by SME.
- SME moves ticket to "Approved for Production"

## **Approved for Production Column: List of Subtasks**
- [ ] Subtask 1(Workflow Reference 8): Technical writer has sent Pull Request.
- [ ] Subtask 2(Workflow Reference 9): SME has committed the document to the repo.
- SME moves the ticket to "Completed" column.
