### ISSUE TITLE
Story: Hardware Chapter

### ISSUE THREAD

**Issue by amsiotdeveloper** [OnionIoT/documentation#44]
# **The Story for a New Chapter:**
### **Task Owner:**
Who owns this task and will approve the final deliverables? 
Lazar

###  1. How does this task relate to the value track(s)?
- All of the effort we put into improving our product lines should provide value to our customers.
- We need to be able to clearly articulate the value each improvement will provide in the following three value tracks:
1. Development
2. Deployment
3. Production
 This chapter will touch on all 3 value tracks.
        
###  2. Create a short statement explaining the objectives and goals for this Chapter.
The objectives of this chapter are to create articles detailing the hardware. 
- The goal is to utilize as much existing content as possible so we can progress quickly through these articles. 
- Articles should be succinct, and minimalist.  
- These are MVP articles, and we will expand on them as users provide feedback and requests.  

### 3. **Reference Material:**
- Provide hyperlinks for helpful and related information. 
https://docs.google.com/spreadsheets/d/1ZLPo1iLGbPXOLvLhcrrmB9wG07G94j2TU6RlS2a7ECU/edit#gid=0

###  1. What are the task owners expectations? 
- After reading these articles the users should be able to evaluate hardware for new designs.  
- They should be able to find the information they need to support their hardware design efforts.
- These articles should become a good reference tool for developers. 

###  2. What does the task owner require for a successful completion of the ticket?
    i.e. sample code, drawings, documents etc.
- MVP: Minimal viable product.  Keep it short, and let's move through these articles quickly.
- Utilize existing content where possible.
- Getting the MVP articles online quickly is important for this chapter and we have time to make improvements later. 

# **Date Required By:**
###  1. When is the scope required to be completed?
no specified date

###  2. Is this a hard date?  Specify if the task is a dependency of another task or if it will impact a customer requirement.
no dependencies 

# **The Workflow:**
- [ ] Subtask 1 (Workflow reference 10): Subject expert created a document of ideas for the new chapter.
- [ ] SME approved the chapter outline.

Subtask 3: PM will create List of tickets for the articles to be created in this chapter:
(Workflow reference 12)
- [x] Task 1 for Article 5.1: Pinouts Ticket #51 
- [x] Task 2 for Article 5.2: GPIO's Ticket #52 
- [x] Task 3 for Article 5.3: Pin Multiplexing Ticket #53 
- [x] Task 4 for Article 5.4: Special Pins Ticket #54 
- [x] Task 5 for Article 5.5: Peripherals Ticket - Heading 
- [x] Task 6 for Article 5.5.1: UART Ticket #55 
- [x] Task 7 for Article 5.5.2: SPI Ticket #56 
- [x] Task 8 for Article 5.5.3: I2C Ticket #57 
- [x] Task 9 for Article 5.5.4: One-Wire Ticket #58 
- [x] Task 10 for Article 5.5.5: Hardware PWM Ticket #59 
- [x] Task 11 for Article 5.5.6: USB Ticket #60 
- [x] Task 12 for Article 5.5.7: SDIO/eMMC Ticket #61 
- [x] Task 13 for Article 5.5.8: Ethernet Ticket #62 
- [x] Task 14 for Article 5.5.9: WiFi Antenna Ticket #64 
- [x] Task 15 for Article 5.6: Device Tree Overlay - Heading 
- [x] Task 16 for Article 5.6.1: Device Tree Overview Ticket #65 
- [x] Task 17 for Article 5.6.2: Software SPI Bus Toclet #66 
- [x] Task 18 for Article 5.6.3: One-Wire Devices Ticket #67 
- [x] Task 19 for Article 5.7: Hardware Accessories - Heading
- [x] Task 20 for Article 5.7.1: LED Chains Ticket #68 
- [x] Task 21 for Article 5.7.2: LTE Modem Ticket #69 
- [ ] make sure article listing in sidebar matches ordering from this ticket
- [ ] make sure all articles have comment sections enabled
- [ ] remove deprecated articles

**Comment by amsiotdeveloper** [comment]
@greenbreakfast please review the hardware chapter outline.  With your approval, I will start making tickets for the list of articles. 
The objective is to have a smooth transition from from OpenWRT chapter to the hardware chapter.   The goal is to have a few article outlines ready for @iammuze by the time the OpenWRT chapter is done.

**Comment by greenbreakfast** [comment]
Just need to complete the last 3 tasks:
- [ ] make sure article listing in sidebar matches ordering from this ticket
- [ ] make sure all articles have comment sections enabled
- [ ] remove deprecated articles

**Comment by amsiotdeveloper** [comment]
the last 3 tasks have been completed and live

**Comment by greenbreakfast** [comment]
great work guys!
