### ISSUE TITLE
Migration to OpenWRT 23.05.2 - Major Release - Part 1

### ISSUE THREAD

**Issue by amsiotdeveloper** [OnionIoT/documentation#45]
### **Task Owner:**
Who owns this task and will approve the final deliverables? 

Lazar

###  1. How does this task relate to the value track(s)?
- All of the effort we put into improving our product lines should provide value to our customers.
- We need to be able to clearly articulate the value each improvement will provide in the following three value tracks:

- This scope is working with the new OpenWRT release so it has a major impact on all 3 value tracks
1. Development
2. Deployment
3. Production
            
###  2. Create a short statement explaining the objectives and goals for this Chapter.

- The goal is to compile and test packages and firmware based on the new OpenWRT release that’s built with the vanilla SDK and Image Builder released by OpenWRT

- *Vanilla = unmodified*

> This is an intermediate step to make the transition smoother. We can identify major issues without the additional variables introduced by using our own customized SDK and Image Builder

### 3. **Reference Material:**
- Provide hyperlinks for helpful and related information. 

- OnionIoT/OpenWRT-Packages
- OnionIoT/openwrt-sdk-wrapper
- OnionIoT/openwrt-imagebuilder-wrapper

###  1. What are the task owners expectations? 

Steps:

1. Create new branch for the release in the OnionIoT/OpenWRT-Packages repo
    1. The branch should be based on the previous release and should be named to match the OpenWRT release name, for example `openwrt-22.03` for OpenWRT 22.03
2. Make changes to support the new release
    1. Update a local copy of the openwrt-sdk-wrapper repo to:
        1. Use the SDK released by OpenWRT for the target release
        2. Use the new branch of the OpenWRT-Packages repo as the package feed
    2. Update a local copy of the openwrt-imagebuilder-wrapper repo  to:
        1. Use the Image Builder released by OpenWRT for the target release
        2. Update omega2 packages repo URL - point to a local location
    3. In the OpenWRT-Packages repo, in the new branch
        1. update the `omega2-base` package version to match the new OpenWRT release
        2. update the `omega2-base` package release number to match the date
3. Build the packages and firmware based on the new release
    - Debug compilation issues as needed

###  2. What does the task owner require for a successful completion of the ticket?
    i.e. sample code, drawings, documents etc.

1. Implement the mentioned steps.
2. Identify and address any issues that arise.
3. Implement the tests in the checklist below and provide test results accordingly. 

# **Date Required By:**
###  1. When is the scope required to be completed?
- no specified completion date
###  2. Is this a hard date?  Specify if the task is a dependency of another task or if it will impact a customer requirement.
- no dependencies 

# **The Workflow:**
- [ ] Subtask 1: Execute the mentioned steps to perform Part 1 of the migration.
- [ ] Subtask 2: Execute the test process in Ticket #46 
- [ ] Subtask 3: Review test results for approval to proceed with Part 2.

**Comment by greenbreakfast** [comment]
@amsiotdeveloper looks good! 

Wanted to add a few notes:
1. We should migrating to the OpenWRT 23.05.2 release - let's update the issue title to include this
2. **Implementation note:** moving forward, we'll try to make OnionIoT/openwrt-packages the only repo that changes with new openwrt releases. To facilitate that, I've moved the sdk and image builder `profile` files into the OnionIoT/openwrt-packages repo.
    - Work to update the CD system to implement this is just about to start
    - The openwrt-sdk-wrapper and openwrt-imagebuilder-wrapper repos will stay the same regardless of the release
