### ISSUE TITLE
Test Plan for Part 2

### ISSUE THREAD

**Issue by amsiotdeveloper** [OnionIoT/documentation#48]
This is a Subtask for Migration to Major Release Part 2 Ticket #47  

# **Task Owner:**
Who owns this task and will approve the final deliverables? 
Lazar

###  1. How does this task relate to the value track(s)?
- All of the effort we put into improving our product lines should provide value to our customers.
- We need to be able to clearly articulate the value each improvement will provide in the following three value tracks:
- This scope is working with the new OpenWRT release so it has a major impact on all 3 value tracks
        1. Development
        2. Deployment
        3. Production
           
###  2. Create a short statement explaining the objectives and goals for this ticket.

- Test the new firmware so it can be approved for release, and debug as needed.
     
# **List of Subtasks:**

Repeat Part 1 Test Procedure on Part 2 firmware:
- [ ] Part 1: Subtask 1: Test for successful boot process 
- [ ] Part 1: Subtask 2:  Test WiFi AP, WiFi STA
- [ ] Part 1: Subtask 3: Test Ethernet networking
- [ ] Part 1: Subtask 4: Test USB and SD Card functionality
- [ ] Part 1: Subtask 5: Test I2C
- [ ] Part 1: Subtask 6: Test GPIO 

Test Part 2 Customized functionality:
- [ ] Part 2: Subtask 7: Test Pin multiplexing
- [ ] Part 2: Subtask 8: Test Hardware PWM
- [ ] Part 2: Subtask 8: Test NodeJS V16
- [ ] Part 2: Subtask 10: Test Device Tree overlay functioning 

# **Reference Material:**
###  1. Provide hyperlinks for helpful and related information. 
- OnionIoT/openwrt-buildsystem-wrapper

# **Deliverables or Desired Outcome:**
###  1. What are the task owners expectations? 
- Execute the test plan, identify any issues and fix as required. 

###  2. What does the task owner require for a successful completion of the ticket?
    i.e. sample code, drawings, documents etc.

- provide test results, text file or screenshots, demonstrating test results with successful setup/commands  
- firmware release commit 

# **Date Required By:**
###  1. When is the scope required to be completed?
- no specified completion date 

###  2. Is this a hard date?  Specify if the task is a dependency of another task or if it will impact a customer requirement.
- Ticket #47  requires these test results to be completed.

**Comment by greenbreakfast** [comment]
closing this issue
replaced with https://github.com/OnionIoT/openwrt-buildsystem-wrapper/issues/25
