### ISSUE TITLE
Story: Networking Chapter

### ISSUE THREAD

**Issue by amsiotdeveloper** [OnionIoT/documentation#78]
# **The Story for a New Chapter:**
### **Task Owner:**
Who owns this task and will approve the final deliverables? 
Lazar

###  1. How does this task relate to the value track(s)?
- All of the effort we put into improving our product lines should provide value to our customers.
- We need to be able to clearly articulate the value each improvement will provide in the following three value tracks:
1. Development
2. Deployment
3. Production
This chapter will touch on all 3 value tracks.
        
###  2. Create a short statement explaining the objectives and goals for this Chapter.

Start with the existing articles in docs/networking in the OnionIoT/documentation repo, and add to them based on the following outlines.

Keep things short and succinct - reuse content where possible. 

When referring to the article outlines, anything in _italics_ is an instruction to the writer. The rest is content that can be used in the article.

### 3. **Reference Material:**
- Provide hyperlinks for helpful and related information. 

https://documentation.onioniot.com/networking/wifi

###  1. What are the task owners expectations? 

After reading this chapter the user should have a good understanding of the networking capabilities using WiFi and Ethernet solutions.  By reading the articles, the user should be able to setup and use either of these networking options.

###  2. What does the task owner require for a successful completion of the ticket?
    i.e. sample code, drawings, documents etc.

detailed explanation with example code demonstrating the application of the networking solution 

# **Date Required By:**
###  1. When is the scope required to be completed?
- no specified date 

###  2. Is this a hard date?  Specify if the task is a dependency of another task or if it will impact a customer requirement.
- no dependancies 
- 
# **The Workflow:**
- [x] Subtask 1 (Workflow reference 10): WiFi Networking Article 4.1 ticket #79 
- [x] Subtask 2(Workflow reference 11): Ethernet Networking Article 4.2 ticket #82 
- [x] Subtask 2(Workflow reference 11): Ethernet Networking Article 4.2 ticket #83 
- [x] Subtask 2(Workflow reference 11): Ethernet Networking Article 4.2 ticket #84
