### ISSUE TITLE
Story: Introduction Chapter

### ISSUE THREAD

**Issue by amsiotdeveloper** [OnionIoT/documentation#97]
# **The Story for a New Chapter:**
### **Task Owner:**
Who owns this task and will approve the final deliverables? 
Lazar

###  1. How does this task relate to the value track(s)?
- All of the effort we put into improving our product lines should provide value to our customers.
- We need to be able to clearly articulate the value each improvement will provide in the following three value tracks:
1. Development
2. Deployment
3. Production
 This chapter is primarily focused on Development for the onboarding of new users, as well as keeping legacy users informed about the latest firmware changes and revision history.  
        
###  2. Create a short statement explaining the objectives and goals for this Chapter.

The objectives of this chapter is to provide new users with clear instructions how to join the Onion community, where to start developing with Omega2, how to use this documentation and how to interact with the community/support etc. 

- The goal is to utilize as much existing content as possible so we can progress quickly through these articles. 
- Articles should be succinct, and minimalist.  

### 3. **Reference Material:**
- Provide hyperlinks for helpful and related information. 
https://docs.google.com/spreadsheets/d/1ZLPo1iLGbPXOLvLhcrrmB9wG07G94j2TU6RlS2a7ECU/edit#gid=0

- 
# **The Workflow:**
- [x] Subtask 1: Introduction to Omega2.  Documentation Roadmap reference 1.1 Ticket #98 
- [x] Subtask 2: Firmware Revision List: Documentation Roadmap reference 1.2 Ticket #106
- [x] Subtask 3: What's New in V23.05.3: Documentation Roadmap reference 1.3 Ticket #107 
- [x] Subtask 4: Comparison of V0.3.4 & v23.05.3: Documentation Roadmap reference 1.4 Ticket #108

**Comment by amsiotdeveloper** [comment]
Intro chapter is completed
